#include "os_settings.h"

/************ POINTER BASED FUNCTIONS *****************/

#define SIV_CREATION_FUNCTION_SIGNATURE(splineDegree) \
LIBEXPORT void * vigra_create_splineimageview##splineDegree##_c (const float *arr, const int width, const int height);

SIV_CREATION_FUNCTION_SIGNATURE(1)
SIV_CREATION_FUNCTION_SIGNATURE(2)
SIV_CREATION_FUNCTION_SIGNATURE(3)
SIV_CREATION_FUNCTION_SIGNATURE(4)
SIV_CREATION_FUNCTION_SIGNATURE(5)


#define SIV_DELETION_FUNCTION_SIGNATURE(splineDegree) \
LIBEXPORT int vigra_delete_splineimageview##splineDegree##_c (void * siv);

SIV_DELETION_FUNCTION_SIGNATURE(1)
SIV_DELETION_FUNCTION_SIGNATURE(2)
SIV_DELETION_FUNCTION_SIGNATURE(3)
SIV_DELETION_FUNCTION_SIGNATURE(4)
SIV_DELETION_FUNCTION_SIGNATURE(5)



#define SIV_OPERATION_FUNCTION_SIGNATURE(function, splineDegree) \
LIBEXPORT float vigra_splineimageview##splineDegree##_##function##_c (void * siv, double x, double y);

SIV_OPERATION_FUNCTION_SIGNATURE(dx,1)
SIV_OPERATION_FUNCTION_SIGNATURE(dx,2)
SIV_OPERATION_FUNCTION_SIGNATURE(dx,3)
SIV_OPERATION_FUNCTION_SIGNATURE(dx,4)
SIV_OPERATION_FUNCTION_SIGNATURE(dx,5)

SIV_OPERATION_FUNCTION_SIGNATURE(dx3,1)
SIV_OPERATION_FUNCTION_SIGNATURE(dx3,2)
SIV_OPERATION_FUNCTION_SIGNATURE(dx3,3)
SIV_OPERATION_FUNCTION_SIGNATURE(dx3,4)
SIV_OPERATION_FUNCTION_SIGNATURE(dx3,5)

SIV_OPERATION_FUNCTION_SIGNATURE(dxx,1)
SIV_OPERATION_FUNCTION_SIGNATURE(dxx,2)
SIV_OPERATION_FUNCTION_SIGNATURE(dxx,3)
SIV_OPERATION_FUNCTION_SIGNATURE(dxx,4)
SIV_OPERATION_FUNCTION_SIGNATURE(dxx,5)

SIV_OPERATION_FUNCTION_SIGNATURE(dxxy,1)
SIV_OPERATION_FUNCTION_SIGNATURE(dxxy,2)
SIV_OPERATION_FUNCTION_SIGNATURE(dxxy,3)
SIV_OPERATION_FUNCTION_SIGNATURE(dxxy,4)
SIV_OPERATION_FUNCTION_SIGNATURE(dxxy,5)

SIV_OPERATION_FUNCTION_SIGNATURE(dxy,1)
SIV_OPERATION_FUNCTION_SIGNATURE(dxy,2)
SIV_OPERATION_FUNCTION_SIGNATURE(dxy,3)
SIV_OPERATION_FUNCTION_SIGNATURE(dxy,4)
SIV_OPERATION_FUNCTION_SIGNATURE(dxy,5)

SIV_OPERATION_FUNCTION_SIGNATURE(dxyy,1)
SIV_OPERATION_FUNCTION_SIGNATURE(dxyy,2)
SIV_OPERATION_FUNCTION_SIGNATURE(dxyy,3)
SIV_OPERATION_FUNCTION_SIGNATURE(dxyy,4)
SIV_OPERATION_FUNCTION_SIGNATURE(dxyy,5)

SIV_OPERATION_FUNCTION_SIGNATURE(dy,1)
SIV_OPERATION_FUNCTION_SIGNATURE(dy,2)
SIV_OPERATION_FUNCTION_SIGNATURE(dy,3)
SIV_OPERATION_FUNCTION_SIGNATURE(dy,4)
SIV_OPERATION_FUNCTION_SIGNATURE(dy,5)

SIV_OPERATION_FUNCTION_SIGNATURE(dy3,1)
SIV_OPERATION_FUNCTION_SIGNATURE(dy3,2)
SIV_OPERATION_FUNCTION_SIGNATURE(dy3,3)
SIV_OPERATION_FUNCTION_SIGNATURE(dy3,4)
SIV_OPERATION_FUNCTION_SIGNATURE(dy3,5)

SIV_OPERATION_FUNCTION_SIGNATURE(dyy,1)
SIV_OPERATION_FUNCTION_SIGNATURE(dyy,2)
SIV_OPERATION_FUNCTION_SIGNATURE(dyy,3)
SIV_OPERATION_FUNCTION_SIGNATURE(dyy,4)
SIV_OPERATION_FUNCTION_SIGNATURE(dyy,5)

SIV_OPERATION_FUNCTION_SIGNATURE(g2,1)
SIV_OPERATION_FUNCTION_SIGNATURE(g2,2)
SIV_OPERATION_FUNCTION_SIGNATURE(g2,3)
SIV_OPERATION_FUNCTION_SIGNATURE(g2,4)
SIV_OPERATION_FUNCTION_SIGNATURE(g2,5)

SIV_OPERATION_FUNCTION_SIGNATURE(g2x,1)
SIV_OPERATION_FUNCTION_SIGNATURE(g2x,2)
SIV_OPERATION_FUNCTION_SIGNATURE(g2x,3)
SIV_OPERATION_FUNCTION_SIGNATURE(g2x,4)
SIV_OPERATION_FUNCTION_SIGNATURE(g2x,5)

SIV_OPERATION_FUNCTION_SIGNATURE(g2xx,1)
SIV_OPERATION_FUNCTION_SIGNATURE(g2xx,2)
SIV_OPERATION_FUNCTION_SIGNATURE(g2xx,3)
SIV_OPERATION_FUNCTION_SIGNATURE(g2xx,4)
SIV_OPERATION_FUNCTION_SIGNATURE(g2xx,5)

SIV_OPERATION_FUNCTION_SIGNATURE(g2xy,1)
SIV_OPERATION_FUNCTION_SIGNATURE(g2xy,2)
SIV_OPERATION_FUNCTION_SIGNATURE(g2xy,3)
SIV_OPERATION_FUNCTION_SIGNATURE(g2xy,4)
SIV_OPERATION_FUNCTION_SIGNATURE(g2xy,5)

SIV_OPERATION_FUNCTION_SIGNATURE(g2y,1)
SIV_OPERATION_FUNCTION_SIGNATURE(g2y,2)
SIV_OPERATION_FUNCTION_SIGNATURE(g2y,3)
SIV_OPERATION_FUNCTION_SIGNATURE(g2y,4)
SIV_OPERATION_FUNCTION_SIGNATURE(g2y,5)

SIV_OPERATION_FUNCTION_SIGNATURE(g2yy,1)
SIV_OPERATION_FUNCTION_SIGNATURE(g2yy,2)
SIV_OPERATION_FUNCTION_SIGNATURE(g2yy,3)
SIV_OPERATION_FUNCTION_SIGNATURE(g2yy,4)
SIV_OPERATION_FUNCTION_SIGNATURE(g2yy,5)


#define SIV_ACCESSOR_FUNCTION_SIGNATURE(splineDegree) \
LIBEXPORT float vigra_splineimageview##splineDegree##_accessor_c(void * siv, double x, double y);

SIV_ACCESSOR_FUNCTION_SIGNATURE(1)
SIV_ACCESSOR_FUNCTION_SIGNATURE(2)
SIV_ACCESSOR_FUNCTION_SIGNATURE(3)
SIV_ACCESSOR_FUNCTION_SIGNATURE(4)
SIV_ACCESSOR_FUNCTION_SIGNATURE(5)



/************ ADDRESS BASED FUNCTIONS *****************/

#define SIV_ADDRESS_CREATION_FUNCTION_SIGNATURE(splineDegree) \
LIBEXPORT unsigned long vigra_create_splineimageview##splineDegree##_address_c (const float *arr, const int width, const int height);

SIV_ADDRESS_CREATION_FUNCTION_SIGNATURE(1)
SIV_ADDRESS_CREATION_FUNCTION_SIGNATURE(2)
SIV_ADDRESS_CREATION_FUNCTION_SIGNATURE(3)
SIV_ADDRESS_CREATION_FUNCTION_SIGNATURE(4)
SIV_ADDRESS_CREATION_FUNCTION_SIGNATURE(5)

#define SIV_DELETION_BY_ADDRESS_FUNCTION_SIGNATURE(splineDegree) \
LIBEXPORT int vigra_delete_splineimageview##splineDegree##_by_address_c (unsigned long address);

SIV_DELETION_BY_ADDRESS_FUNCTION_SIGNATURE(1)
SIV_DELETION_BY_ADDRESS_FUNCTION_SIGNATURE(2)
SIV_DELETION_BY_ADDRESS_FUNCTION_SIGNATURE(3)
SIV_DELETION_BY_ADDRESS_FUNCTION_SIGNATURE(4)
SIV_DELETION_BY_ADDRESS_FUNCTION_SIGNATURE(5)


#define SIV_OPERATION_BY_ADDRESS_FUNCTION_SIGNATURE(function, splineDegree) \
LIBEXPORT float vigra_splineimageview##splineDegree##_##function##_by_address_c (unsigned long address, double x, double y);

SIV_OPERATION_BY_ADDRESS_FUNCTION_SIGNATURE(dx,1)
SIV_OPERATION_BY_ADDRESS_FUNCTION_SIGNATURE(dx,2)
SIV_OPERATION_BY_ADDRESS_FUNCTION_SIGNATURE(dx,3)
SIV_OPERATION_BY_ADDRESS_FUNCTION_SIGNATURE(dx,4)
SIV_OPERATION_BY_ADDRESS_FUNCTION_SIGNATURE(dx,5)

SIV_OPERATION_BY_ADDRESS_FUNCTION_SIGNATURE(dx3,1)
SIV_OPERATION_BY_ADDRESS_FUNCTION_SIGNATURE(dx3,2)
SIV_OPERATION_BY_ADDRESS_FUNCTION_SIGNATURE(dx3,3)
SIV_OPERATION_BY_ADDRESS_FUNCTION_SIGNATURE(dx3,4)
SIV_OPERATION_BY_ADDRESS_FUNCTION_SIGNATURE(dx3,5)

SIV_OPERATION_BY_ADDRESS_FUNCTION_SIGNATURE(dxx,1)
SIV_OPERATION_BY_ADDRESS_FUNCTION_SIGNATURE(dxx,2)
SIV_OPERATION_BY_ADDRESS_FUNCTION_SIGNATURE(dxx,3)
SIV_OPERATION_BY_ADDRESS_FUNCTION_SIGNATURE(dxx,4)
SIV_OPERATION_BY_ADDRESS_FUNCTION_SIGNATURE(dxx,5)

SIV_OPERATION_BY_ADDRESS_FUNCTION_SIGNATURE(dxxy,1)
SIV_OPERATION_BY_ADDRESS_FUNCTION_SIGNATURE(dxxy,2)
SIV_OPERATION_BY_ADDRESS_FUNCTION_SIGNATURE(dxxy,3)
SIV_OPERATION_BY_ADDRESS_FUNCTION_SIGNATURE(dxxy,4)
SIV_OPERATION_BY_ADDRESS_FUNCTION_SIGNATURE(dxxy,5)

SIV_OPERATION_BY_ADDRESS_FUNCTION_SIGNATURE(dxy,1)
SIV_OPERATION_BY_ADDRESS_FUNCTION_SIGNATURE(dxy,2)
SIV_OPERATION_BY_ADDRESS_FUNCTION_SIGNATURE(dxy,3)
SIV_OPERATION_BY_ADDRESS_FUNCTION_SIGNATURE(dxy,4)
SIV_OPERATION_BY_ADDRESS_FUNCTION_SIGNATURE(dxy,5)

SIV_OPERATION_BY_ADDRESS_FUNCTION_SIGNATURE(dxyy,1)
SIV_OPERATION_BY_ADDRESS_FUNCTION_SIGNATURE(dxyy,2)
SIV_OPERATION_BY_ADDRESS_FUNCTION_SIGNATURE(dxyy,3)
SIV_OPERATION_BY_ADDRESS_FUNCTION_SIGNATURE(dxyy,4)
SIV_OPERATION_BY_ADDRESS_FUNCTION_SIGNATURE(dxyy,5)

SIV_OPERATION_BY_ADDRESS_FUNCTION_SIGNATURE(dy,1)
SIV_OPERATION_BY_ADDRESS_FUNCTION_SIGNATURE(dy,2)
SIV_OPERATION_BY_ADDRESS_FUNCTION_SIGNATURE(dy,3)
SIV_OPERATION_BY_ADDRESS_FUNCTION_SIGNATURE(dy,4)
SIV_OPERATION_BY_ADDRESS_FUNCTION_SIGNATURE(dy,5)

SIV_OPERATION_BY_ADDRESS_FUNCTION_SIGNATURE(dy3,1)
SIV_OPERATION_BY_ADDRESS_FUNCTION_SIGNATURE(dy3,2)
SIV_OPERATION_BY_ADDRESS_FUNCTION_SIGNATURE(dy3,3)
SIV_OPERATION_BY_ADDRESS_FUNCTION_SIGNATURE(dy3,4)
SIV_OPERATION_BY_ADDRESS_FUNCTION_SIGNATURE(dy3,5)

SIV_OPERATION_BY_ADDRESS_FUNCTION_SIGNATURE(dyy,1)
SIV_OPERATION_BY_ADDRESS_FUNCTION_SIGNATURE(dyy,2)
SIV_OPERATION_BY_ADDRESS_FUNCTION_SIGNATURE(dyy,3)
SIV_OPERATION_BY_ADDRESS_FUNCTION_SIGNATURE(dyy,4)
SIV_OPERATION_BY_ADDRESS_FUNCTION_SIGNATURE(dyy,5)

SIV_OPERATION_BY_ADDRESS_FUNCTION_SIGNATURE(g2,1)
SIV_OPERATION_BY_ADDRESS_FUNCTION_SIGNATURE(g2,2)
SIV_OPERATION_BY_ADDRESS_FUNCTION_SIGNATURE(g2,3)
SIV_OPERATION_BY_ADDRESS_FUNCTION_SIGNATURE(g2,4)
SIV_OPERATION_BY_ADDRESS_FUNCTION_SIGNATURE(g2,5)

SIV_OPERATION_BY_ADDRESS_FUNCTION_SIGNATURE(g2x,1)
SIV_OPERATION_BY_ADDRESS_FUNCTION_SIGNATURE(g2x,2)
SIV_OPERATION_BY_ADDRESS_FUNCTION_SIGNATURE(g2x,3)
SIV_OPERATION_BY_ADDRESS_FUNCTION_SIGNATURE(g2x,4)
SIV_OPERATION_BY_ADDRESS_FUNCTION_SIGNATURE(g2x,5)

SIV_OPERATION_BY_ADDRESS_FUNCTION_SIGNATURE(g2xx,1)
SIV_OPERATION_BY_ADDRESS_FUNCTION_SIGNATURE(g2xx,2)
SIV_OPERATION_BY_ADDRESS_FUNCTION_SIGNATURE(g2xx,3)
SIV_OPERATION_BY_ADDRESS_FUNCTION_SIGNATURE(g2xx,4)
SIV_OPERATION_BY_ADDRESS_FUNCTION_SIGNATURE(g2xx,5)

SIV_OPERATION_BY_ADDRESS_FUNCTION_SIGNATURE(g2xy,1)
SIV_OPERATION_BY_ADDRESS_FUNCTION_SIGNATURE(g2xy,2)
SIV_OPERATION_BY_ADDRESS_FUNCTION_SIGNATURE(g2xy,3)
SIV_OPERATION_BY_ADDRESS_FUNCTION_SIGNATURE(g2xy,4)
SIV_OPERATION_BY_ADDRESS_FUNCTION_SIGNATURE(g2xy,5)

SIV_OPERATION_BY_ADDRESS_FUNCTION_SIGNATURE(g2y,1)
SIV_OPERATION_BY_ADDRESS_FUNCTION_SIGNATURE(g2y,2)
SIV_OPERATION_BY_ADDRESS_FUNCTION_SIGNATURE(g2y,3)
SIV_OPERATION_BY_ADDRESS_FUNCTION_SIGNATURE(g2y,4)
SIV_OPERATION_BY_ADDRESS_FUNCTION_SIGNATURE(g2y,5)

SIV_OPERATION_BY_ADDRESS_FUNCTION_SIGNATURE(g2yy,1)
SIV_OPERATION_BY_ADDRESS_FUNCTION_SIGNATURE(g2yy,2)
SIV_OPERATION_BY_ADDRESS_FUNCTION_SIGNATURE(g2yy,3)
SIV_OPERATION_BY_ADDRESS_FUNCTION_SIGNATURE(g2yy,4)
SIV_OPERATION_BY_ADDRESS_FUNCTION_SIGNATURE(g2yy,5)


#define SIV_ACCESSOR_BY_ADDRESS_FUNCTION_SIGNATURE(splineDegree) \
LIBEXPORT float vigra_splineimageview##splineDegree##_accessor_by_address_c(unsigned long address, double x, double y);

SIV_ACCESSOR_BY_ADDRESS_FUNCTION_SIGNATURE(1)
SIV_ACCESSOR_BY_ADDRESS_FUNCTION_SIGNATURE(2)
SIV_ACCESSOR_BY_ADDRESS_FUNCTION_SIGNATURE(3)
SIV_ACCESSOR_BY_ADDRESS_FUNCTION_SIGNATURE(4)
SIV_ACCESSOR_BY_ADDRESS_FUNCTION_SIGNATURE(5)
